import type { Metadata } from "next";
import { Alex_Brush, Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import MenuItems from "./MenuItems";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alexBrush = Alex_Brush({
  weight: "400",
  variable: "--font-alex-brush",
  subsets: ["latin"],
});

const circular = localFont({
  src: [
    {
      path: "../fonts/CircularStd-Black.woff",
      style: "black",
      weight: "900",
    },
    {
      path: "../fonts/CircularStd-Bold.woff",
      style: "bold",
      weight: "700",
    },
    {
      path: "../fonts/CircularStd-Medium.woff",
      style: "medium",
      weight: "500",
    },
    {
      path: "../fonts/CircularStd-Book.woff",
      style: "normal",
      weight: "400",
    },
  ],
  variable: "--font-circular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) {
  console.log(sidebar);

  return (
    <html lang="en">
      <body
        className={`${circular.variable} ${geistSans.variable} ${geistMono.variable} ${alexBrush.variable} antialiased`}
      >
        <div className="flex h-screen">
          <div
            className="flex-2/5 overflow-y-auto border-1 p-10"
            style={{ scrollbarGutter: "stable" }}
          >
            <MenuItems />
            {sidebar}
          </div>
          <div className="w-96 flex-3/5 overflow-y-scroll p-10">
            <div className="aspect-[1/1.4] max-w-[1000px] bg-white p-10 shadow-lg">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
