@startuml db_schema

hide circle
skinparam linetype ortho

!define primary_key(x) <b><&key> x</b>
!define column(x) <&media-record> x

entity "minutes" as minutes {
  primary_key( id ): SERIAL
  --
  *file : TEXT
  *number : INTEGER
  *createad_date : DATE
}


@enduml
