@startuml db_schema

hide circle
skinparam linetype ortho

!define primary_key(x) <b><&key> x</b>
!define foreign_key(x) <i><&key> x</i>
!define column(x) <&media-record> x

entity "committees" as committees {
  primary_key( id ): int IDENTITY
  --
  name: TEXT
  password: TEXT
}

entity "minutes" as minutes {
  primary_key( id ): int IDENTITY
  --
  foreign_key( committee_id ): INTEGER <<FK>>
  filename : TEXT
  blobUrl: TEXT
  number: TEXT
  created: DATE
}

committees ||--o{ minutes

@enduml